### ISSUE TITLE
Possibility to add Bigfoot Killer NIC 2100

### ISSUE THREAD

**Issue by tkurbad** [Sakura-IT/SonnetAmiga#46] opened 2019-02-21 17:03 UTC
Hi,

since the Bigfoot Killer NICs K1/M1 are now very hard to come by, and since I happen to have a Killer NIC 2100 with 400MHz "NPU" lying around, might it be possible to:

a) Run this card in an PCI to PCI-E adapter like this one https://www.startech.com/Cards-Adapters/Slot-Extension/PCI-to-PCI-Express-Adapter-Card~PCI1PEX1 (I can't imagine why this shouldn't work, but perhaps someone here knows better)
b) In the above configuration, support this card via the sonnet.library.

Thanks in advance,
Torsten

**Comment by tkurbad** [comment] 2019-02-22 14:48
Just to add: The Bigfoot Killer 2100 seemingly is a low cost version of the Killer Xeno Pro. The latter has the various headers (Sound and USB) populated, but seems to be identical when it comes to the processor and on board RAM (128 MB). Thus, supporting this line of almost identical PCI-E NICs would again open up two distinct possibilities. This is especially interesting, since the Xeno Pro seems to be more widely used in the US while the 2100 is more readily available in Europe.

**Comment by MastaTabs** [comment] 2019-04-12 11:12
AFAIK the Mediator PCI Bridge doesn't support PCI configuration type 1 and because of that doesn't support PCI-PCIe bridges or PCI-PCI bridges. These would be needed to drive such a card in a Mediator PCI slot.

**Comment by tkurbad** [comment] 2019-04-15 08:35
> AFAIK the Mediator PCI Bridge doesn't support PCI configuration type 1 and because of that doesn't support PCI-PCIe bridges or PCI-PCI bridges.

That's a pity.

**Comment by rkujawa** [comment] 2019-04-15 08:48
I'll leave a final comment on this for @DvdBoon, but upon closer investigation that seems indeed, to be the case here.

**Comment by DvdBoon** [comment] 2019-04-15 23:36
Sadly enough, this is exactly the case. Therefore this feature can not be implemented on the current hardware.

**Comment by DvdBoon** [comment] 2022-01-08 11:44
Prometheus and Mediator MKIV appear to support config 1 cycles. On the Prometheus, the PCIe NIC is detected. However, the 128 MB RAM does not show, only 64kb. Not sure how to proceed from here. @tkurbad

**Comment by tkurbad** [comment] 2022-01-08 22:18
Thanks for looking into this again. I don't know how to proceed either. Can I be of any help? Could it be that the card has some internal firmware that needs to be disabled (like it is done with a jumper wire for the Apocalypse 128 MB version)?

**Comment by DvdBoon** [comment] 2024-01-14 19:28
I tested my Killer 2000 some more after various upgrades and fixes to the Prometheus library. I am not sure if my card is broken as registers that should be linked (you write in one and it shows up in the other too) don't seem to work. They work as intended on the PCI versions of the network card. So if you are still here @tkurbad i need someone to check his card if it works correctly.

**Comment by DvdBoon** [comment] 2024-01-14 19:30
Writing the reset ASCII word to the reset register also doesn't trigger a reset ready signal for example. Other cards beyond the bridge do seem to work though, so the suspicion of a faulty card is strong.

**Comment by tkurbad** [comment] 2024-01-15 09:46
> I tested my Killer 2000 some more after various upgrades and fixes to the Prometheus library. I am not sure if my card is broken as registers that should be linked (you write in one and it shows up in the other too) don't seem to work. They work as intended on the PCI versions of the network card. So if you are still here @tkurbad i need someone to check his card if it works correctly.

Thanks for looking further into this. My machine is currently in pieces, and I don't even know if I still have the Killer 2100. But I can take a look later on (perhaps in a few days.)

**Comment by DvdBoon** [comment] 2024-01-16 17:27
The stupid thing is that I was banging the PCI registers but should of course use the PCIe registers. I am able to set-up and address the 128MB that is on-board the card.

Reset documentation regarding the MPC8134E seems to be faulty. I need a soft reset anyway and the MPC8134E does not seem to have that in software (unlike the MPC8343EA on the PCI K1/M1). I am looking at the watchdog timers to trigger a reset so I can insert the start-up code for the powerpc.library.

**Comment by DvdBoon** [comment] 2024-02-13 23:33
It has been made clear that the card is not at fault but the Firestorm FW is. I am closing this issue here as i no longer support this version of the powerpc library. I'll open a new one in the other repository.

**Closed as completed by DvdBoon** 2024-02-13 23:33 UTC
Labels: enhancement, question
